sudo: false

language: cpp

compiler:
  - gcc

addons:
  apt_packages:
    - ccache
    - libboost-all-dev
    - flex
    - bison
    - libssl-dev
    - libpq-dev
    - libmysqlclient-dev
    - libedit-dev
    - libyajl-dev
    - libwxbase3.0-dev
    - libwxgtk3.0-dev

before_script:
  - mkdir build
  - cd build
  - export PATH="/usr/lib/ccache:$PATH"
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/tmp/icinga2

script:
  - make && make test && make install && /tmp/icinga2/sbin/icinga2 --version
