site_name: Icinga 2
docs_dir: doc
dev_addr: 0.0.0.0:8000
pages:
- [1-about.md, About Icinga 2]
- [2-getting-started.md, Getting Started]
- [3-monitoring-basics.md, Monitoring Basics]
- [4-configuring-icinga-2.md, Configuring Icinga 2]
- [5-service-monitoring.md, Service Monitoring]
- [6-distributed-monitoring.md, Distributed Monitoring]
- [7-agent-based-monitoring.md, Agent Based Monitoring]
- [8-advanced-topics.md, Advanced Topics]
- [9-object-types.md, Object Types]
- [10-icinga-template-library.md, Icinga Template Library]
- [11-cli-commands.md, CLI Commands]
- [12-icinga2-api.md, Icinga 2 API]
- [13-addons.md, Addons]
- [14-features.md, Features]
- [15-troubleshooting.md, Troubleshooting]
- [16-upgrading-icinga-2.md, Upgrading Icinga 2]
- [17-language-reference.md, Language Reference]
- [18-library-reference.md, Library Reference]
- [19-script-debugger.md, Script Debugger]
- [20-development.md, Development]
- [21-selinux.md, SELinux]
- [22-migrating-from-icinga-1x.md, Migrating from Icinga 1.x]
- [23-appendix.md, Appendix]
theme: readthedocs
markdown_extensions: [smarty]
extra_javascript: [scroll.js]
include_search: true
